import openai
from wyaitt_sketches.core.settings import settings
openai.api_key = settings.openai_token


class BaseStrategy:

    @staticmethod
    def _get_completion(prompt, actor="a chatbot"):
        """
        Generate text completion for a given prompt using the OpenAI GPT-3 language model.

        :param prompt: Text prompt to generate completion for.
        :return: Text generated by the model as the first "choice" in the JSON response object, with leading and
        trailing whitespace removed.
        """
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "user", "content": f"You are {actor}"},
                {"role": "user", "content": prompt},
            ]
        )
        completion = response.choices[0].message.content
        return completion
